Dropdown
fac30/PRO03_FRONT_DANI_WILL_BEN pull request #2
Opened 2024-10-01 20:45 UTC by william-man

created first version of core components

2024-10-01 21:21 UTC, bescka requested changes

2024-10-01 21:21 UTC, bescka commented on src/components/Button.tsx
Just a thought - in /Button.tsx you've passed ```classes``` as a required value in the interface but then given a default value in the component. In the interface you can make this consistent this by making the classes prop optional: ```classes?: string;```

2024-10-01 21:21 UTC, bescka commented on src/components/Display.tsx
Maybe bug with score rendering on the first question if the score is either NaN or 0?

2024-10-01 21:21 UTC, bescka commented on src/components/DropDown.tsx
You've used a fragment but there is only one top level element anyway. defaultValue required in interface but has default value "" in component. Might be onChange rather than onSelect for the <select> element.

2024-10-02 11:14 UTC, merged

2024-10-03 16:27 UTC, camelPhonso commented on src/components/Display.tsx
WHAT?